### PR TITLE
Fixes some problems with orthography and rebuilds data.

### PR DESCRIPTION
**Pull request by tresoldi**
As discussed in issue https://github.com/lexibank/naganorgyalrongic/issues/4

### CODE REVIEW

**Comment by LinguList** [comment]
A pity, as I'd have liked to see the changes, but the diff is re-ordered, so I cannot see what exactly you changed: the schwa? These were untouched from the profile, but it is very good that they are accounted for now. You made sure to double-check against aliases in clts? This was the reason, why we did not notice the retroflex affricates before...

**Comment by tresoldi** [comment]
Right, it would have been better to first run the replacements, and in a second moment do the reordering. The sorting that is to make diffing easier made the diff impossible this first time.

As there were no manual changes, I added a flag for order preservation to my script and ran it on your last commit. Here is the diff: https://gist.github.com/tresoldi/970e012cc46b47dbd972b573fb82ebc0

**Comment by tresoldi** [comment]
Here is an interesting case:

```diff
468c468
< ɚ	ɚ
---
> ɚ	ə˞
```

**Comment by LinguList** [comment]
Indeed. I thought I had already changed all retroflex affricates, so that's why I was surprised, but it's good they are done now, and this brought us to have a closer look at clts and at the sanity of the profile already in teh profile itself, not inside lexibank checking.

**Pull request merged**
